---
- hosts: "{{ host | default('web') }}"
  become: yes
  gather_facts: no
  pre_tasks:
    - name: "{{ app_name }} setup"
      when: update_app is defined and update_app
      block:
        - name: sync {{ app_name }} binary
          include_role:
            name: "{{ app_sync_role_name }}"
        - name: get {{ app_name }} version
          include_role:
            name: "{{ app_get_role_name }}"
  roles:
    - role: traffic_delete_monitor
      when: traffic_meter is defined and traffic_meter
    - role: "{{ app_role_name }}"