---
- name: Get latest gost download url
  shell: curl -Lso- https://api.github.com/repos/ginuerzh/gost/releases/latest | python -m json.tool | grep -E "browser_download_url.*gost-linux-amd64" | awk '{print $2}' | xargs echo
  register: gost_latest_download_url

- name: Download latest gost from Github and unarchive gost
  get_url:
    url: "{{ gost_latest_download_url.stdout }}"
    dest: roles/app/files/gost.gz

- name: Remote old gost binary
  file:
    path: roles/app/files/gost
    state: absent

- name: Unzip gost binary
  shell: gunzip roles/app/files/gost.gz
