---
- name: Get latest shadowsocks_go download url
  shell: curl -Lso- https://api.github.com/repos/shadowsocks/shadowsocks-go/releases/latest | python -m json.tool | grep -E "browser_download_url.*shadowsocks-server\.tar\.gz" | awk '{print $2}' | xargs echo
  register: shadowsocks_go_latest_download_url
- name: Get latest shadowsocks_go2 download url
  shell: curl -Lso- https://api.github.com/repos/shadowsocks/go-shadowsocks2/releases | python -m json.tool | grep -E "browser_download_url.*shadowsocks2-linux\.gz" | head -n 1 | awk '{print $2}' | xargs echo
  register: shadowsocks_go2_latest_download_url

- name: Download latest shadowsocks_go from Github
  get_url:
    url: "{{ shadowsocks_go_latest_download_url.stdout }}"
    dest: roles/app/files/shadowsocks_go.tar.gz
- name: Download latest shadowsocks_go2 from Github
  get_url:
    url: "{{ shadowsocks_go2_latest_download_url.stdout }}"
    dest: roles/app/files/shadowsocks_go2.gz

- name: Remote old shadowsocks_go binary
  file:
    path: roles/app/files/shadowsocks_go
    state: absent
- name: Remote old shadowsocks_go2 binary
  file:
    path: roles/app/files/shadowsocks_go2
    state: absent

- name: Unzip shadowsocks_go binary
  shell: tar -xzf roles/app/files/shadowsocks_go.tar.gz -C roles/app/files
- name: Unzip shadowsocks_go2 binary
  shell: gunzip roles/app/files/shadowsocks_go2.gz