---
- name: Get latest tiny_port_mapper download url
  shell: curl -Lso- https://api.github.com/repos/wangyu-/tinyPortMapper/releases/latest  | python -m json.tool | grep -E "browser_download_url" | awk '{print $2}' | xargs echo
  register: tiny_port_mapper_latest_download_url

- name: Remote old tiny_port_mapper binary
  file:
    path: roles/app/files/tiny_port_mapper
    state: absent

- name: Download latest tiny_port_mapper from Github
  get_url:
    url: "{{ tiny_port_mapper_latest_download_url.stdout }}"
    dest: roles/app/files/tiny_port_mapper.tar.gz

- name: Unzip tiny_port_mapper binary
  shell: tar -xzf roles/app/files/tiny_port_mapper.tar.gz -C roles/app/files

- name: Rename tiny port mapper binary
  copy:
    src: roles/app/files/tinymapper_amd64
    dest: roles/app/files/tiny_port_mapper
    remote_src: yes
    follow: yes